Changed bandwidth monitor

diff --git a/environment/wm/i3/files/user/.blocklets/bandwidth b/environment/wm/i3/files/user/.blocklets/bandwidth
--- a/environment/wm/i3/files/user/.blocklets/bandwidth
+++ b/environment/wm/i3/files/user/.blocklets/bandwidth
@@ -1,125 +1,115 @@
 #!/bin/bash
-# Copyright (C) 2012 Stefan Breunig <stefan+measure-net-speed@mathphys.fsk.uni-heidelberg.de>
-# Copyright (C) 2014 kaueraal
-# Copyright (C) 2015 Thiago Perrotta <perrotta dot thiago at poli dot ufrj dot br>
+#
+# Copyright (C) 2015 James Murphy
+# Licensed under the terms of the GNU GPL v2 only.
+#
+# i3blocks blocklet script to monitor bandwidth usage
 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
+iface="${BLOCK_INSTANCE}"
+iface="${IFACE:-$iface}"
+dt="${DT:-3}"
+unit="Mb"
 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
+function default_interface {
+    ip route | awk '/^default via/ {print $5; exit}'
+}
 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+function check_proc_net_dev {
+    if [ ! -f "/proc/net/dev" ]; then
+        echo "/proc/net/dev not found"
+        exit 1
+    fi
+}
 
-# Get custom IN and OUT labels if provided by command line arguments
-while [[ $# -gt 1 ]]; do
-    key="$1"
-    case "$key" in
-        -i|--inlabel)
-            INLABEL="$2"
-            shift;;
-        -o|--outlabel)
-            OUTLABEL="$2"
-            shift;;
+function list_interfaces {
+    check_proc_net_dev
+    echo "Interfaces in /proc/net/dev:"
+    grep -o "^[^:]\\+:" /proc/net/dev | tr -d " :"
+}
+
+while getopts d:i:t:u:p:lh opt; do
+    case "$opt" in
+        d) direction="$OPTARG";;
+        i) iface="$OPTARG" ;;
+        t) dt="$OPTARG" ;;
+        u) unit="$OPTARG" ;;
+        p) printf_command="$OPTARG" ;;
+        l) list_interfaces && exit 0 ;;
+        h) printf \
+"Usage: bandwidth3 [-i interface] [-t time] [-u unit] [-p printf_command] [-l] [-h]
+Options:
+-i\tNetwork interface to measure. Default determined using \`ip route\`.
+-t\tTime interval in seconds between measurements. Default: 3
+-u\tUnits to measure bytes in. Default: Mb
+\tAllowed units: Kb, KB, Mb, MB, Gb, GB, Tb, TB
+\tUnits may have optional it/its/yte/ytes on the end, e.g. Mbits, KByte
+-p\tAwk command to be called after a measurement is made.
+\tDefault: printf \"<span font='FontAwesome'>  </span>%%-5.1f/%%5.1f %%s/s\\\\n\", rx, wx, unit;
+\tExposed variables: rx, wx, tx, unit, iface
+-l\tList available interfaces in /proc/net/dev
+-h\tShow this help text
+" && exit 0;;
     esac
-    shift
 done
 
-[[ -z $INLABEL ]] && INLABEL=""
-[[ -z $OUTLABEL ]] && OUTLABEL=""
-
-# Use the provided interface, otherwise the device used for the default route.
-if [[ -n $BLOCK_INSTANCE ]]; then
-  INTERFACE=$BLOCK_INSTANCE
-else
-  INTERFACE=$(ip route | awk '/^default/ { print $5 ; exit }')
-fi
-
-# Issue #36 compliant.
-
-if ! [[ $INTERFACE = *"tun"* ]]; then
-  if ! [ -e "/sys/class/net/${INTERFACE}/operstate" ] || ! [ "`cat /sys/class/net/${INTERFACE}/operstate`" = "up" ]
-  then
-      echo "$INTERFACE down"
-      echo "$INTERFACE down"
-      echo "#FF0000"
-      exit 0
-  fi
-fi
-
-# path to store the old results in
-path="/dev/shm/$(basename $0)-${INTERFACE}"
-
-# grabbing data for each adapter.
-read rx < "/sys/class/net/${INTERFACE}/statistics/rx_bytes"
-read tx < "/sys/class/net/${INTERFACE}/statistics/tx_bytes"
-
-# get time
-time=$(date +%s)
-
-# write current data if file does not exist. Do not exit, this will cause
-# problems if this file is sourced instead of executed as another process.
-if ! [[ -f "${path}" ]]; then
-  echo "${time} ${rx} ${tx}" > "${path}"
-  chmod 0666 "${path}"
-fi
-
-# read previous state and update data storage
-read old < "${path}"
-echo "${time} ${rx} ${tx}" > "${path}"
-
-# parse old data and calc time passed
-old=(${old//;/ })
-time_diff=$(( $time - ${old[0]} ))
-
-# sanity check: has a positive amount of time passed
-[[ "${time_diff}" -gt 0 ]] || exit
-
-# calc bytes transferred, and their rate in byte/s
-rx_diff=$(( $rx - ${old[1]} ))
-tx_diff=$(( $tx - ${old[2]} ))
-rx_rate=$(( $rx_diff / $time_diff ))
-tx_rate=$(( $tx_diff / $time_diff ))
-
-# shift by 10 bytes to get KiB/s. If the value is larger than
-# 1024^2 = 1048576, then display MiB/s instead
-
-case "$1" in
-  "in") #IN
-    echo -n "$INLABEL"
-    rx_kib=$(( $rx_rate >> 10 ))
-    if hash bc 2>/dev/null && [[ "$rx_rate" -gt 1048576 ]]; then
-      printf '%sM' "`echo "scale=1; $rx_kib / 1024" | bc`"
-    else
-        echo -n "${rx_kib}K"
-    fi;;
-  "out") #OUT
-    echo -n "$OUTLABEL"
-    tx_kib=$(( $tx_rate >> 10 ))
-    if hash bc 2>/dev/null && [[ "$tx_rate" -gt 1048576 ]]; then
-      printf '%sM' "`echo "scale=1; $tx_kib / 1024" | bc`"
-    else
-      echo -n "${tx_kib}K"
-    fi;;
-  "both") #BOTH
-    echo -n "$INLABEL"
-    rx_kib=$(( $rx_rate >> 10 ))
-    if hash bc 2>/dev/null && [[ "$rx_rate" -gt 1048576 ]]; then
-      printf '%sM' "`echo "scale=1; $rx_kib / 1024" | bc`"
-    else
-        echo -n "${rx_kib}K"
-    fi
-    echo -n " "
-    echo -n "$OUTLABEL"
-    tx_kib=$(( $tx_rate >> 10 ))
-    if hash bc 2>/dev/null && [[ "$tx_rate" -gt 1048576 ]]; then
-      printf '%sM' "`echo "scale=1; $tx_kib / 1024" | bc`"
-    else
-      echo -n "${tx_kib}K"
-    fi;;
+case "$direction" in
+  in)
+      LABEL="${LABEL:-<span font='FontAwesome'></span>}" # down arrow
+      printf_command="${PRINTF_COMMAND:-"printf \"${LABEL}%5.1f %s/s\\n\", rx, unit;"}";;
+  out)
+      LABEL="${LABEL:-<span font='FontAwesome'></span>}" # up arrow
+      printf_command="${PRINTF_COMMAND:-"printf \"${LABEL}%5.1f %s/s\\n\", wx, unit;"}";;
+  *)
+      LABEL="${LABEL:-<span font='FontAwesome'> </span>}" # down arrow up arrow
+      printf_command="${PRINTF_COMMAND:-"printf \"${LABEL}%-5.1f/%5.1f %s/s\\n\", rx, wx, unit;"}";;
 esac
+
+check_proc_net_dev
+
+iface="${iface:-$(default_interface)}"
+while [ -z "$iface" ]; do
+    echo No default interface
+    sleep "$dt"
+    iface=$(default_interface)
+done
+
+case "$unit" in
+    Kb|Kbit|Kbits)   bytes_per_unit=$((1024 / 8));;
+    KB|KByte|KBytes) bytes_per_unit=$((1024));;
+    Mb|Mbit|Mbits)   bytes_per_unit=$((1024 * 1024 / 8));;
+    MB|MByte|MBytes) bytes_per_unit=$((1024 * 1024));;
+    Gb|Gbit|Gbits)   bytes_per_unit=$((1024 * 1024 * 1024 / 8));;
+    GB|GByte|GBytes) bytes_per_unit=$((1024 * 1024 * 1024));;
+    Tb|Tbit|Tbits)   bytes_per_unit=$((1024 * 1024 * 1024 * 1024 / 8));;
+    TB|TByte|TBytes) bytes_per_unit=$((1024 * 1024 * 1024 * 1024));;
+    *) echo Bad unit "$unit" && exit 1;;
+esac
+
+scalar=$((bytes_per_unit * dt))
+init_line=$(cat /proc/net/dev | grep "^[ ]*$iface:")
+if [ -z "$init_line" ]; then
+    echo Interface not found in /proc/net/dev: "$iface"
+    exit 1
+fi
+
+init_received=$(awk '{print $2}' <<< $init_line)
+init_sent=$(awk '{print $10}' <<< $init_line)
+
+(while true; do cat /proc/net/dev; sleep "$dt"; done) |\
+    stdbuf -oL grep "^[ ]*$iface:" |\
+    awk -v scalar="$scalar" -v unit="$unit" -v iface="$iface" '
+BEGIN{old_received='"$init_received"';old_sent='"$init_sent"'}
+{
+    received=$2
+    sent=$10
+    rx=(received-old_received)/scalar;
+    wx=(sent-old_sent)/scalar;
+    tx=rx+wr;
+    old_received=received;
+    old_sent=sent;
+    if(rx >= 0 && wx >= 0){
+        '"$printf_command"';
+        fflush(stdout);
+    }
+}
+'
